/**
 * @versemate/lexicon — public entry point.
 *
 * Provides chapter-aligned Greek/Hebrew lexicon data for the VerseMate
 * Bible reader. Consumed by verse-mate-web (Vite) and verse-mate-mobile
 * (Expo / React Native). Both bundlers can statically resolve the
 * generated chapter manifest in `manifest.generated.ts`.
 *
 * Public API:
 *   - `loadAlignmentFor(bookId, chapter)`: async, returns the merged
 *     ChapterAlignment (generated chapter data + hand-curated lemma
 *     definitions for theologically loaded words).
 *   - `getBookSlug(bookId)`: helper for callers that need the slug
 *     directly (e.g. building a contextual cache key).
 *   - Type re-exports.
 *
 * Bundler notes:
 *   - Metro: `manifest.generated.ts` is 1,189 literal `import()` paths,
 *     which Metro static-analyses at build time. Each chapter is its
 *     own code-split chunk.
 *   - Vite: `import()` works the same way — Vite is happy with literal
 *     paths and lazily fetches each chapter.
 *
 * The `_lemmas.json` (16 MB) and `_contextual.json` files are also
 * `import()`-ed lazily and cached at the module level so the user pays
 * the cost at most once per session.
 */

import { CHAPTER_LOADERS } from './manifest.generated';
import { LEXICON as HAND_LEXICON } from './lemmas';
import { getBookSlug } from './book-slugs';
import type {
  ChapterAlignment,
  LemmaKey,
  LexEntry,
} from './types';
import type {
  ContextualGlosses,
  GeneratedAlignment,
  GeneratedLexicon,
} from './internal-types';

let generatedLexiconPromise: Promise<GeneratedLexicon> | null = null;
function loadGeneratedLexicon(): Promise<GeneratedLexicon> {
  if (!generatedLexiconPromise) {
    generatedLexiconPromise = import('./generated/_lemmas.json').then(
      (m) => m.default as GeneratedLexicon,
    );
  }
  return generatedLexiconPromise;
}

let contextualPromise: Promise<ContextualGlosses> | null = null;
function loadContextual(): Promise<ContextualGlosses> {
  if (!contextualPromise) {
    contextualPromise = import('./generated/_contextual.json').then((m) => {
      // The _meta key is informational only — strip it so it can never
      // accidentally match a lemma lookup. Two-step cast through `unknown`
      // because TS infers `_meta` as a concrete object shape from the JSON
      // import and refuses the direct `& { _meta?: unknown }` widening.
      const raw = m.default as unknown as Record<string, unknown>;
      const { _meta, ...rest } = raw;
      void _meta;
      return rest as ContextualGlosses;
    });
  }
  return contextualPromise;
}

/**
 * Cross-translation surface aliases keyed by lemma slug. Generated by
 * scripts/generate_aliases.py — for each top-frequency lemma, a list of
 * English surfaces used across KJV, NASB, ESV, NIV, BSB, NLT, ASV, NRSV.
 *
 * Solves the BSB↔NASB drift problem: BSB's "perseverance" alignment
 * surface for hupomone doesn't substring-match NASB's "endurance" or
 * KJV's "longsuffering"; the alias list lets the renderer try each
 * variant against the displayed page text.
 */
type SurfaceAliases = Record<string, readonly string[]>;
let aliasesPromise: Promise<SurfaceAliases> | null = null;
function loadAliases(): Promise<SurfaceAliases> {
  if (!aliasesPromise) {
    aliasesPromise = import('./generated/_aliases.json').then((m) => {
      const raw = m.default as unknown as Record<string, unknown>;
      const { _meta, ...rest } = raw;
      void _meta;
      return rest as SurfaceAliases;
    });
  }
  return aliasesPromise;
}

// Cache: alignments by `${bookId}:${chapter}`. Populated lazily by
// loadAlignmentFor as users open chapters.
const alignmentCache: Map<string, ChapterAlignment> = new Map();

/**
 * Async lookup. Lazy-loads the per-chapter JSON + (on first hit) the
 * shared lemmas file, then merges with the HAND_LEXICON overrides so
 * theologically loaded words keep their richer entries.
 *
 * Returns `null` if the book/chapter has no alignment data.
 */
/**
 * Whole-lexicon structures, built once per process rather than per chapter.
 *
 * `loadAlignmentFor` used to rebuild both of these on every chapter that was not already
 * in its cache: an 18,100-key object spread and an `Object.entries` pass over the result.
 * Neither depends on the chapter. Measured at ~45ms per chapter on a Raspberry Pi 5, and
 * more on a phone, repeated for every chapter a reader opens.
 *
 * Keyed on the generated lexicon's identity so a hot reload that swaps the module rebuilds
 * rather than serving a stale index.
 */
let mergedLexiconCache: { source: unknown; value: Record<LemmaKey, LexEntry> } | null = null;

function getMergedLexicon(generatedLexicon: GeneratedLexicon): Record<LemmaKey, LexEntry> {
  if (mergedLexiconCache && mergedLexiconCache.source === generatedLexicon) {
    return mergedLexiconCache.value;
  }
  const value: Record<LemmaKey, LexEntry> = {
    ...(generatedLexicon as Record<LemmaKey, LexEntry>),
    ...HAND_LEXICON,
  };
  mergedLexiconCache = { source: generatedLexicon, value };
  return value;
}

let strongsToSlugCache: { source: unknown; value: Record<string, LemmaKey> } | null = null;

function getStrongsToSlug(mergedLexicon: Record<LemmaKey, LexEntry>): Record<string, LemmaKey> {
  if (strongsToSlugCache && strongsToSlugCache.source === mergedLexicon) {
    return strongsToSlugCache.value;
  }
  const value: Record<string, LemmaKey> = {};
  for (const [lemmaSlug, entry] of Object.entries(mergedLexicon)) {
    const sKey = normalizeStrongs(entry?.strongs);
    if (sKey && !(sKey in value)) value[sKey] = lemmaSlug;
  }
  strongsToSlugCache = { source: mergedLexicon, value };
  return value;
}

/**
 * Columnar light lexicon, as written by `scripts/build_lemma_index.py`.
 *
 * Column order matches `slugs`, index for index. `pos` is dictionary-encoded and `loaded` ships as a
 * list of indices, both because on a projection this small the field NAMES dominate — repeating five
 * keys 18,100 times costs more than the values do (2.48MB row-oriented vs 1.15MB this way).
 */
interface LightLexiconFile {
  slugs: string[];
  lemma: string[];
  translit: string[];
  strongs: string[];
  posVocab: string[];
  pos: number[];
  basicGloss: string[];
  loadedIdx: number[];
}

let lightLexiconPromise: Promise<Record<LemmaKey, LexEntry>> | null = null;

/**
 * The lexicon a chapter actually needs, at 1/16th the weight.
 *
 * `loadGeneratedLexicon` awaits an 18.7MB file, and `loadAlignmentFor` awaits it on the FIRST chapter
 * a reader opens. On a phone that is a single ~2s block of the JS thread, measured across four
 * independent captures in verse-mate-mobile (worst JS block 1991ms / 1946ms / 2163ms / 2207ms). It is
 * deferred past first paint so startup is unaffected — but any swipe or tab switch landing inside that
 * window freezes outright, while everything else being optimised in that reader is tens of ms.
 *
 * 12.1MB of that file is `notes` + `related` + `semanticRange`, read only when a reader TAPS a word.
 * Chapter load needs: whether a lemma has an entry at all (the renderer's `if (!entry) continue` gates
 * the underline), its `strongs` (homograph disambiguation), and `translit` / `basicGloss` / `loaded`,
 * which the mobile renderer reads while rendering for accessibility labels and the context-sensitive
 * marker.
 *
 * Every field here is one of `LexEntry`'s REQUIRED fields, deliberately: a light entry satisfies
 * `LexEntry` structurally, so no consumer needs a type change and only the popover — which reads the
 * optional prose — has to opt into `lookupLemma`.
 *
 * HAND_LEXICON is merged on top with the same precedence as `getMergedLexicon`, and costs nothing
 * extra: it is a static import already in the bundle. Those ~144 entries stay FULL, so a
 * theologically loaded word keeps its prose even here.
 */
function loadLightLexicon(): Promise<Record<LemmaKey, LexEntry>> {
  if (!lightLexiconPromise) {
    lightLexiconPromise = import('./generated/_lemmas-light.json').then((m) => {
      const file = m.default as unknown as LightLexiconFile;
      const loaded = new Set(file.loadedIdx);
      const out: Record<LemmaKey, LexEntry> = {};
      for (let i = 0; i < file.slugs.length; i += 1) {
        const posIndex = file.pos[i];
        const entry: LexEntry = {
          lemma: file.lemma[i],
          translit: file.translit[i],
          strongs: file.strongs[i],
          pos: posIndex >= 0 ? file.posVocab[posIndex] : '',
          basicGloss: file.basicGloss[i],
        };
        if (loaded.has(i)) entry.loaded = true;
        out[file.slugs[i]] = entry;
      }
      return { ...out, ...HAND_LEXICON };
    });
  }
  return lightLexiconPromise;
}

/**
 * Full entry for one lemma, paying for the 18.7MB file on first use.
 *
 * The other half of the light path: the prose has to come from somewhere, and a word tap is the right
 * moment to pay for it — user-initiated, rare, and already asynchronous. Returns the same merged shape
 * `loadAlignmentFor`'s `lexicon` gives on the full path, so a popover can switch to this without
 * changing anything it renders.
 */
export async function lookupLemma(slug: LemmaKey): Promise<LexEntry | null> {
  const generated = await loadGeneratedLexicon();
  return getMergedLexicon(generated)[slug] ?? null;
}

export interface LoadAlignmentOptions {
  /**
   * Skip the 18.7MB lemma file and use the light projection instead.
   *
   * `lexicon` still answers "does this lemma exist" and carries `strongs`, `lemma`, `translit`,
   * `pos`, `basicGloss` and `loaded` — everything a chapter needs to render. The optional prose
   * (`notes`, `semanticRange`, `related`) is absent; fetch it per lemma with `lookupLemma` when a
   * reader opens a definition.
   *
   * Opt-in rather than the default so existing callers (verse-mate-web) are untouched.
   */
  lite?: boolean;
}

export async function loadAlignmentFor(
  bookId: number,
  chapter: number,
  options: LoadAlignmentOptions = {},
): Promise<ChapterAlignment | null> {
  const lite = options.lite === true;
  // Lite and full results are cached SEPARATELY. They differ in what `lexicon` holds, so one shared
  // key would let whichever caller arrived first decide what every later caller gets — a popover
  // quietly losing its prose because something else asked for lite a moment earlier.
  const key = `${lite ? 'lite:' : ''}${bookId}:${chapter}`;
  const cached = alignmentCache.get(key);
  if (cached) return cached;

  const slug = getBookSlug(bookId);
  if (!slug) return null;
  const loader = CHAPTER_LOADERS[`${slug}-${chapter}`];
  if (!loader) return null;

  const [chapterMod, resolvedLexicon, contextual, aliases] = await Promise.all([
    loader(),
    // The whole point of `lite`: never await the 18.7MB file here.
    lite ? loadLightLexicon() : loadGeneratedLexicon().then(getMergedLexicon),
    loadContextual(),
    loadAliases(),
  ]);
  const raw: GeneratedAlignment = chapterMod.default;

  // Hand-curated lemma entries win on collision — preserves the rich
  // James-1 contextual glosses + semantic ranges for words like λόγος,
  // ὑπομονή.
  //
  // HOISTED: built once, not per chapter. Neither this merge nor the Strong's
  // index below depends on the chapter, and both walk the whole 18,100-entry
  // lexicon — measured at ~45ms per chapter on a Pi 5, more on a phone. It was
  // being repeated for every chapter a reader opened.
  // Already merged above — full or light, depending on `options.lite`. `getStrongsToSlug` below is
  // keyed on this object's identity, so each variant gets its own cached index rather than one
  // poisoning the other.
  const mergedLexicon = resolvedLexicon;

  // Strong's-number → lemma slug, inverted from the merged lexicon. The
  // generated alignment slug collapses homographs (Hebrew אֵת obj-marker H0853 /
  // plowshare H0855 and עֵת "time" H6256 all slugify to "et"; רֵעַ "neighbor"
  // H7453 / "shouting" H7452 both → "rea"), so a token's bare `lemma` alone
  // resolves to the single slug-collision winner — the wrong sense for every
  // other homograph occurrence. The per-token Strong's (now emitted into the
  // chapter data) disambiguates: we map it to the displaced slug that carries
  // the right sense (e.g. H6256 → "et_h6256" → "time"). Keyed via
  // normalizeStrongs so it matches the token's canonical G####/H#### form.
  const strongsToSlug = getStrongsToSlug(mergedLexicon);

  // Build each token's full surface list. The generated alignment file
  // ships ONE BSB-anchored surface; we union it with the cross-translation
  // aliases (KJV/NASB/ESV/NIV/...) so the renderer's substring scan can
  // find a match regardless of which translation the API is currently
  // serving. Per-occurrence contextual glosses overlay in the same pass.
  const mergedVerses: ChapterAlignment['verses'] = {};
  for (const [verseStr, tokens] of Object.entries(raw.verses)) {
    mergedVerses[Number(verseStr)] = (
      tokens as { surface: string; lemma: string; strongs?: string }[]
    ).map((t) => {
      const lemmaAliases = aliases[t.lemma];
      // Dedupe (case-insensitive) — BSB surface is often already in the
      // alias list, no point matching twice. Preserve the BSB surface
      // first so it remains the canonical anchor.
      const seen = new Set<string>([t.surface.toLowerCase()]);
      const surfaces: string[] = [t.surface];
      if (lemmaAliases) {
        for (const a of lemmaAliases) {
          const key = a.toLowerCase();
          if (!seen.has(key)) {
            seen.add(key);
            surfaces.push(a);
          }
        }
      }
      const k = `${slug}:${raw.chapter}:${verseStr}:${t.lemma}`;
      // Re-point the lemma the renderer resolves the DEFINITION from to the
      // Strong's-correct slug (homograph disambiguation — see strongsToSlug).
      // Underline matching still uses the original slug's cross-translation
      // surfaces above, and contextual glosses stay keyed on the original
      // lemma; only which lexicon entry the popover shows changes. Falls back
      // to the original slug when the token has no Strong's or no distinct
      // entry maps to it (the overwhelmingly common non-homograph case:
      // strongsToSlug[token.strongs] === t.lemma, so this is a no-op).
      const normStrongs = normalizeStrongs(t.strongs);
      const effLemma = (normStrongs && strongsToSlug[normStrongs]) || t.lemma;
      const base = surfaces.length === 1
        ? { surface: t.surface, lemma: effLemma }
        : { surface: surfaces, lemma: effLemma };
      return contextual[k] ? { ...base, contextual: contextual[k] } : base;
    });
  }

  const alignment: ChapterAlignment = {
    bookId: raw.bookId,
    book: raw.book,
    chapter: raw.chapter,
    version: raw.version,
    verses: mergedVerses,
    lexicon: mergedLexicon,
    themeLemmas: raw.themeLemmas,
  };
  alignmentCache.set(key, alignment);
  return alignment;
}

/**
 * Strong's-number → lemma entry index.
 *
 * Keyed on canonical `G####` / `H####` form (4-digit zero-padded), the same
 * format the backend stores in `verses.tokens` and emits over the wire when
 * a chapter is requested with `?tagged=1`. The renderer's per-token lookup
 * is then a simple `STRONGS_INDEX[token.strongs]` — no normalization needed
 * at render time.
 *
 * Built from the same `_lemmas.json` blob `loadAlignmentFor` uses, overlaid
 * with `HAND_LEXICON` so theologically loaded words (logos, sarx, hupomonē,
 * dikaiosynē, …) keep their hand-curated semantic ranges + notes. The
 * collision rule mirrors `loadAlignmentFor`'s mergedLexicon: hand entries
 * win.
 *
 * Async, lazy-loaded, cached — same pattern as `loadGeneratedLexicon`. The
 * underlying JSON only fetches the first time a tagged chapter renders.
 */
function normalizeStrongs(raw: string | undefined): string | null {
  if (!raw) return null;
  // Drop disambiguator suffix letters (e.g. "G0007a" → "G0007"), zero-pad
  // to 4 digits. Matches the backend's parse_tbe normalization so frontend
  // lookups land on the same canonical key the wire uses.
  const m = /^([GH])(\d+)([A-Za-z]?)$/.exec(raw.trim());
  if (!m) return null;
  return `${m[1]}${m[2].padStart(4, '0')}`;
}

let strongsIndexPromise: Promise<Readonly<Record<string, LexEntry>>> | null = null;

/**
 * Returns the lazy-loaded Strong's index. Pre-load this alongside chapter
 * data so render-time `STRONGS_INDEX[token.strongs]` lookups are
 * synchronous. Safe to call concurrently — the underlying JSON fetch and
 * merge happens at most once per session.
 */
export function loadStrongsIndex(): Promise<Readonly<Record<string, LexEntry>>> {
  if (!strongsIndexPromise) {
    strongsIndexPromise = loadGeneratedLexicon().then((generatedLexicon) => {
      const index: Record<string, LexEntry> = {};
      // 1. Index every generated entry by its Strong's (already padded).
      for (const entry of Object.values(generatedLexicon)) {
        if (!entry) continue;
        const key = normalizeStrongs(entry.strongs);
        if (key) index[key] = entry;
      }
      // 2. Overlay HAND_LEXICON — wins on collision. HAND_LEXICON uses
      // unpadded form ("G80"); normalize to match backend wire shape.
      for (const entry of Object.values(HAND_LEXICON)) {
        const key = normalizeStrongs(entry.strongs);
        if (key) index[key] = entry;
      }
      return Object.freeze(index);
    });
  }
  return strongsIndexPromise;
}

export { getBookSlug, BOOK_SLUGS } from './book-slugs';
export type {
  ChapterAlignment,
  LexEntry,
  AlignedToken,
  LemmaKey,
  RelatedWord,
} from './types';
